services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/model:/app/model
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: ./backend
    command: sh -c 'while [ ! -f model/model.pkl ]; do echo "⏳ Waiting for model..."; sleep 2; done; celery -A tasks worker --loglevel=info'
    volumes:
      - ./backend:/app
      - ./backend/model:/app/model
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
