services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/model:/app/model
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - redis
  worker:
    build: ./backend
    command: sh -c 'while [ ! -f model/model.pkl ]; do echo "⏳ Waiting for model..."; sleep 2; done; celery -A tasks worker --loglevel=info'
    volumes:
      - ./backend:/app
      - ./backend/model:/app/model
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend/my-ml-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    volumes:
      - ./frontend/my-ml-frontend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./frontend/my-ml-frontend/.env
